apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w67bc0a88-python
  janus-idp.io/tekton: w67bc0a88-python
  backstage.io/kubernetes-id: w67bc0a88-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w67bc0a88-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
